### ISSUE TITLE
'this' is undefined inside beforeEach/afterEach/it/fit

### ISSUE THREAD

**Issue by MikeDimmick** [matthewjh/jasmine-promises#4]
I'm trying to make use of jasmine-promises in a promise-heavy codebase. Our current practice is to expect that the promise is resolved (or rejected as appropriate) inside a promise.finally handler (we're using Q.js promises). It can be hard to track down promise failures when this occurs. jasmine-promises looks like it will simplify the tests and ensure that errors are reported.

We have some complicated fixtures that need extensive set-up. We attach data and mock objects/spies to the fixture by using the object that jasmine passes to the `beforeEach` function, then subsequently to the `it` function, as the `this` pointer.

After enabling jasmine-promises, all existing tests that make use of `this` are failing with a `TypeError: Cannot set property 'xxx' of undefined` error.

This is a blocker preventing us from using jasmine-promises at all.

Minimum reproducible case:

```
describe('fixture', function() {
    beforeEach(function() {
        this.field = 'value';
    });

    it('should set `this` correctly', function() {
        expect(this.field).toEqual('value');
    });
});
```

Without loading jasmine-promises the test passes. After loading jasmine-promises, you get:

```
Chrome 48.0.2564 (Windows 7 0.0.0) fixture should set `this` correctly FAILED
        TypeError: Cannot set property 'field' of undefined
            at [...]/jasmine-promises.unit.js:6:24
            at Object.arguments.(anonymous function) ([...]/node_modules/jasmine-promises/
dist/jasmine-promises.js:39:23)
            at Object.arguments.(anonymous function) ([...]/node_modules/jasmine-promises/
dist/jasmine-promises.js:51:11)
        TypeError: Cannot read property 'field' of undefined
            at [...]/jasmine-promises.unit.js:10:24
            at Object.arguments.(anonymous function) ([...]/node_modules/jasmine-promises/
dist/jasmine-promises.js:39:23)
```

The behaviour of the `this` pointer is documented at [Jasmine 2.2 introduction.js - The this keyword](http://jasmine.github.io/2.2/introduction.html#section-The_<code>this</code>_keyword)

**Comment by MikeDimmick** [comment]
Sorry, after attempting to fix this myself, and not able to reproduce by adding tests to passes.spec.js, I find that I can't reproduce this in a standalone repo! We do require() our tests, I'll see if that makes a difference.

**Comment by matthewjh** [comment]
Hi Mike,

Thanks for taking the time to do this. I'm going to take a look at this in greater detail over the weekend.

Thanks :)

@MikeDimmick

**Comment by matthewjh** [comment]
Hi Mike,

Thanks again. v0.4.1 should fix this issue.

Please try it out and let me know how it goes.

**Comment by MikeDimmick** [comment]
Looks good. Thanks for doing this.

**Comment by matthewjh** [comment]
You're welcome. Let me know if you encounter any other issues!
