### ISSUE TITLE
Error running jasmine-promises

### ISSUE THREAD

**Issue by torontocode** [matthewjh/jasmine-promises#7]
I'm getting an error when I try and use jasmine-promises.
The error is:
`Error: Cannot find module './patch' from '[PATH TO NODE_MODULES]/node_modules/jasmine-promises/dist'`
I see the call to require patch.js in the code, but no such file exists in dist/ 
I'm sure it's something simple I'm doing wrong.
Any help would be much appreciated.

**Comment by matthewjh** [comment]
Hi @torontocode,

It works for me. Please can you detail how you're including jasmine-promises in your project?

The project is packaged with browserify, and the `./patch` require should resolve to the inline 'module' here https://github.com/matthewjh/jasmine-promises/blob/master/dist/jasmine-promises.js#L14

**Comment by torontocode** [comment]
Sure: 
in karma.conf.js:
`
frameworks: [ 'browserify', 'jasmine' ],
preprocessors: {
      'tests/**/*.test.js': [ 'browserify' ]
    }
`
and then in client.service.test.js:
`require('jasmine-promises');`
I see the module inline in my code, but it doesn't get found and I get the above error.

**Comment by torontocode** [comment]
I tried adding the path to the file in karma.conf.js and it works fine.
I'm going to close this issue because I don't think there is a problem with this NPM module, I think the problem lies with using require() in test files. It doesn't work as expected.

**Comment by matthewjh** [comment]
Ah. Maybe the issue is that you're using browserify to pre-process your test specs, which will cause it to process `jasmine-promises`. `require('jasmine-promises')` will execute code already packaged via browserify, which may be the problem -- it's trying to package code that's already browserified. 

That's just a theory. I can look into this further.
