### ISSUE TITLE
Excessively long stack traces

### ISSUE THREAD

**Issue by martinsson** [matthewjh/jasmine-promises#9]
Hi great work on this module!

I get strange stack traces when a test fails. Here's an example

	Error: index must be defined in /myProject/src/entities/Face.js (line 9)
	/myProject/src/entities/Face.js:9:1841
	/myProject/tests/entities/FaceSpec.js:21:82
	/myProject/node_modules/jasmine-promises/dist/jasmine-promises.js:35:34
	/myProject/node_modules/jasmine-promises/dist/jasmine-promises.js:47:15
	/myProject/node_modules/jasmine-promises/dist/jasmine-promises.js:47:15
	/myProject/node_modules/jasmine-promises/dist/jasmine-promises.js:47:15
	/myProject/node_modules/jasmine-promises/dist/jasmine-promises.js:47:15
	/myProject/node_modules/jasmine-promises/dist/jasmine-promises.js:47:15
	/myProject/node_modules/jasmine-promises/dist/jasmine-promises.js:47:15
	/myProject/node_modules/jasmine-promises/dist/jasmine-promises.js:47:15
	/myProject/node_modules/jasmine-promises/dist/jasmine-promises.js:47:15
	/myProject/node_modules/jasmine-promises/dist/jasmine-promises.js:47:15
	/myProject/node_modules/jasmine-promises/dist/jasmine-promises.js:47:15
       ..... this continues for another 40 lines ....

Any idea how to limit this?

**Comment by jahumes** [comment]
+1

**Comment by marialq** [comment]
+1

**Comment by matthewjh** [comment]
Thanks! I've just pushed a fix for this. 

Let me know of any further issues.
